CREATE TABLE users (
    id INT PRIMARY KEY IDENTITY,
    email NVARCHAR(255) UNIQUE NOT NULL,
    passwrd NVARCHAR(255) NOT NULL,
    time_created DATETIME DEFAULT GETDATE(),
    role NVARCHAR(50) NOT NULL
);
